set(BROWSER_VERSION_MAJOR 0)
set(BROWSER_VERSION_MINOR 1)
set(BROWSER_VERSION_PATCH 1)
set(BROWSER_VERSION_BUILD 0)
set(BROWSER_VERSION_STRING "${BROWSER_VERSION_MAJOR}.${BROWSER_VERSION_MINOR}")

if(BROWSER_VERSION_BUILD GREATER 0)
    set(BROWSER_VERSION_STRING "${BROWSER_VERSION_STRING}.${BROWSER_VERSION_PATCH}.${BROWSER_VERSION_BUILD}")
elseif(BROWSER_VERSION_PATCH GREATER 0)
    set(BROWSER_VERSION_STRING "${BROWSER_VERSION_STRING}.${BROWSER_VERSION_PATCH}")
endif()

# Numeric-only version string; i.e. 1.0.7.3
set(BROWSER_VERSION_STRING_REAL ${BROWSER_VERSION_STRING})

# TODO: Re-enable git tags when this mess is sorted out
# Human-readable version string; i.e. 1.0.8-beta1
# git_append_shorttag(BROWSER_VERSION_STRING)

set(AXR_README_FILE "${CMAKE_SOURCE_DIR}/README.md")
set(AXR_LICENSE_FILE "${CMAKE_SOURCE_DIR}/LICENSE")

set(AXR_README_FILE_TXT "${CMAKE_BINARY_DIR}/README.txt")
set(AXR_LICENSE_FILE_TXT "${CMAKE_BINARY_DIR}/LICENSE.txt")
